# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: Self-Hosted-Agent
  demands: agent.name -equals FortifyAgent01

steps:

- task: CmdLine@2
  inputs:
    script: |
      echo Write your commands here
      
      echo Hello world
      "C:\\Program Files\\Fortify\\Fortify_SCA_and_Apps_22.1.0\\bin\\scancentral.bat" -url "https://10.30.100.56:8443/scancentral-ctrl/" start -bt none -application "riches-azure" -version "v1" -b riches_azure -upload -uptoken 63770e04-fd31-465e-89e3-45336433095c
